version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[Dependabot]: "
    versioning-strategy: increase
    ignore:
      - dependency-name: "react"
        versions: ["18.3.1"]
      - dependency-name: "tailwindcss"
        versions: ["3.4.17"]
      - dependency-name: "postcss"
        versions: ["8.5.1"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions: ["6.21.0"]
      - dependency-name: "@typescript-eslint/parser"
        versions: ["6.21.0"]
      - dependency-name: "react-dom"
        versions: ["18.3.1"]
      - dependency-name: "@types/react-dom"
        versions: ["18.3.5"]
      - dependency-name: "typescript"
        versions: ["5.7.2"]
      - dependency-name: "vitest"
        versions: ["2.2.4"]
      - dependency-name: "vitest-coverage-v8"
        versions: ["2.2.4"]
        
    labels:
      - "dependencies" 