version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[Dependabot]: "
    versioning-strategy: increase
    ignore:
      - dependency-name: "react"
        versions: ["18.3.1"]
    labels:
      - "dependencies" 