repos:
  - repo: local
    hooks:
      - id: pytest
        name: run server and tests
        entry: bash -c 'python server/app.py & sleep 2 && pytest -v server; kill $!'
        language: system
        pass_filenames: false
        always_run: true