repos:
  - repo: local
    hooks:
      - id: pytest
        name: run pytest for server
        entry: bash -c 'python server/app.py & sleep 2 && pytest -v server; kill $!'
        language: system
        pass_filenames: false
        always_run: true
      
      - id: eslint
        name: run eslint for client
        entry: bash -c 'cd client && npm run lint'
        language: system
        pass_filenames: false
        always_run: true

      - id: vitest
        name: run vitest for client
        entry: bash -c 'cd client && npm run test'
        language: system
        pass_filenames: false
        always_run: true

      - id: black
        name: run black for server linting
        entry: bash -c 'black --line-length 120 server'
        language: system
        pass_filenames: false
        always_run: true

      - id: isort
        name: run isort for server
        entry: bash -c 'isort --profile black server'
        language: system
        pass_filenames: false
        always_run: true
